port: 3000
bindIP: 0.0.0.0
db:
  type: postgres
  host: db
  port: 5432
  user: wikijs
  pass: wikijsrocks
  db: wiki
logLevel: info

minio:
  endPoint: minio
  Region: wiki.jx.com
  port: 9000
  useSSL: false
  accessKey: wikiminio
  secretKey: jxhyroot
  bucketName: wikipicture

dataPath: /data/wiki/data

# ---------------------------------------------------------------------
# Body Parser Limit
# ---------------------------------------------------------------------
# Maximum size of API requests body that can be parsed. Does not affect
# file uploads.

bodyParserLimit: 5mb

jwt:
  unit: hours
  amount: 48
