# -- DEV DOCKER-COMPOSE --
# -- DO NOT USE IN PRODUCTION! --

version: "3"
services:
  db:
    container_name: wiki-db
    image: postgres:9-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    volumes:
      - /data/postgresql/data:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  adminer:
    container_name: wiki-adminer
    image: adminer:latest
    logging:
      driver: "none"
    ports:
      - "3001:8080"

  # solr:
  #   container_name: wiki-solr
  #   image: solr:7-alpine
  #   logging:
  #     driver: "none"
  #   ports:
  #     - "8983:8983"
  #   volumes:
  #     - solr-data:/opt/solr/server/solr/mycores
  #   entrypoint:
  #     - docker-entrypoint.sh
  #     - solr-precreate
  #     - wiki

  minio:
      image: minio/minio
      container_name: minio
      restart: always
      ports:
        #暴露API接口
        - 9000:9000
        #暴露Web接口控制台端口
        - 9001:9001
      command: minio server /data --console-address ":9001"

      environment:
        MINIO_ACCESS_KEY: wikiminio    #管理后台用户名
        MINIO_SECRET_KEY: jxhyroot #管理后台密码，最小8个字符
      volumes:
        - /data/wiki/minio:/data           #映射当前目录下的data目录至容器内/data目录
        - /data/wiki/minio/config:/root/.minio/     #映射配置目录

  wiki:
    container_name: wiki-app
    build:
      context: ../..
      dockerfile: dev/containers/Dockerfile
    command: sh build.sh
    depends_on:
      - db
      - minio
    links:
      - db
      - minio
    ports:
      - "80:3000"
    volumes:
      - ../..:/wiki
      - /wiki/node_modules
      - /wiki/.git
      - /data/wiki:/data/wiki


volumes:
  db-data:
  # solr-data:
